// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportWeb.Data.EF;

namespace SupportWeb.Data.Migrations
{
    [DbContext(typeof(SupportShopDbContext))]
    [Migration("20200508175009_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SupportWeb.Data.Entities.KhachHang", b =>
                {
                    b.Property<Guid>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NguoiChiuTrachNhiem")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("NhanSuPhuTrachMa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoDienThoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(11)
                        .HasDefaultValue(0);

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ThongTinSupport")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Ma");

                    b.ToTable("KhacHang");
                });

            modelBuilder.Entity("SupportWeb.Data.Entities.NhanSu", b =>
                {
                    b.Property<Guid>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BoPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoDienThoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(11)
                        .HasDefaultValue(0);

                    b.HasKey("Ma");

                    b.ToTable("NhanSu");

                    b.HasData(
                        new
                        {
                            Ma = new Guid("aed723a2-9ad3-4f2a-8753-da1b06ea5520"),
                            BoPhan = 3,
                            ChucVu = "Leader",
                            HoTen = "Đinh Xuân Quyết",
                            SoDienThoai = 963555396
                        },
                        new
                        {
                            Ma = new Guid("fba9d758-5204-4e31-a2ea-d1466e947f23"),
                            BoPhan = 3,
                            ChucVu = "Leader",
                            HoTen = "Trần Gia Bảo",
                            SoDienThoai = 0
                        });
                });

            modelBuilder.Entity("SupportWeb.Data.Entities.RequestKH", b =>
                {
                    b.Property<Guid>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodeMa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FormThucHien")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<Guid>("KhachHangMa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KyThuatMa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiYeuCau")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Ma");

                    b.HasIndex("CodeMa");

                    b.HasIndex("KhachHangMa");

                    b.ToTable("RequestKH");
                });

            modelBuilder.Entity("SupportWeb.Data.Entities.RequestKH", b =>
                {
                    b.HasOne("SupportWeb.Data.Entities.NhanSu", "NhanSu")
                        .WithMany("RequestKH")
                        .HasForeignKey("CodeMa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupportWeb.Data.Entities.KhachHang", "KhachHang")
                        .WithMany("RequestKH")
                        .HasForeignKey("KhachHangMa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
